[build]
  # Netlify usually detects static sites, but this ensures it looks in the root
  publish = "." 
  # A dummy command to prevent it from looking for a build script if none exists
  command = "echo 'Deploying Static HTML Site'"

[build.environment]
  # Using a specific version number (20.11.1) to satisfy strict nvm requirements
  NODE_VERSION = "20.11.1"